### ISSUE TITLE
inconsistent use of "Testbarkeit" and "Verifizierbarkeit"

### ISSUE THREAD

**Issue by happychameleon** [unibas-sweng/software-engineering#21]
in the slide deck "Software Qualitätsmerkmale",  "Testbarkeit (verifiability)" is mentioned when the whole list of quality characteristics of software is shown, but when it goes into detail about "Testbarkeit" the word "Verifizierbarkeit" is used.

**Comment by marcelluethi** [comment]
Thanks for pointing this out. I will change it such that it is consistent.
